In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
dataset=pd.read_csv("Churn_Modelling.csv")

In [ ]:
x= dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encode',OneHotEncoder(),[1])],remainder="passthrough")
x=ct.fit_transform(x)
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [ ]:
print(y_train)

[0 0 0 ... 0 0 1]


In [ ]:
print(y_test)

[0 1 0 ... 0 0 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
ann=tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
ann.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [ ]:
ann.fit(x_train,y_train,batch_size= 32,epochs=110)

Epoch 1/110
250/250 [==============================] - 1s 2ms/step - loss: 0.3359 - accuracy: 0.8661
Epoch 2/110
250/250 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8631
Epoch 3/110
250/250 [==============================] - 1s 2ms/step - loss: 0.3367 - accuracy: 0.8661
Epoch 4/110
250/250 [==============================] - 1s 2ms/step - loss: 0.3365 - accuracy: 0.8646
Epoch 5/110
250/250 [==============================] - 1s 2ms/step - loss: 0.3365 - accuracy: 0.8644
Epoch 6/110
250/250 [==============================] - 1s 2ms/step - loss: 0.3362 - accuracy: 0.8636
Epoch 7/110
250/250 [==============================] - 1s 2ms/step - loss: 0.3359 - accuracy: 0.8650
Epoch 8/110
250/250 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8637
Epoch 9/110
250/250 [==============================] - 1s 2ms/step - loss: 0.3361 - accuracy: 0.8659
Epoch 10/110
250/250 [==============================] - 0s 2ms/step - loss: 0.3364 - accura

In [ ]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5

1/1 [==============================] - 0s 34ms/step


array([[False]])

In [ ]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1509   86]
 [ 189  216]]


0.8625